disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  # - unused_setter_value
  # - identifier_name
  # - function_body_length
  # - nesting
  # - notification_center_detachment
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - NordSecurity
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Carthage
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
cyclomatic_complexity: 24
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
large_tuple:
  warning: 4
  error: 5
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 250
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
function_body_length:
  warning: 55
  error: 80
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    warning: 1
    error: 1 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
